#!/bin/sh

# This value is set by install.sh
ROOT_CONFIG=

WHITELIST="$ROOT_CONFIG/whitelist"
WHITELIST_CUSTOM="$ROOT_CONFIG/whitelist.dist"
CONFIG_FILE_DIR="$ROOT_CONFIG/.php-cs-fixer.dist.php"
PHP_CS_FIXER_DIR="$ROOT_CONFIG/vendor/bin/php-cs-fixer"

WHITELISTED=0
GIT_REPO=$(git remote -v)

# Loops through all lines in the given file and checks if the
# current repository is present.
function is_whitelisted () {
  while IFS="" read -r line || [ -n "$line" ]; do
    if [[ $GIT_REPO =~ $line ]]; then
      echo 1
      exit
    fi
  done < "$1"

  echo 0
}

WHITELISTED=$(is_whitelisted "$WHITELIST")

# If not already whitelisted, and there is a custom whitelist file in the directory
if [[ $WHITELISTED == 0 && -f "$WHITELIST_CUSTOM" ]]; then
  WHITELISTED=$(is_whitelisted "$WHITELIST_CUSTOM")
fi

# Repository not whitelisted. Do not run php-cs-fixer
if [ $WHITELISTED == 0 ]; then
    exit 0;
fi

echo "Running php-cs-fixer pre-commit routine"
FAILED=0

# Run PHP CS Fixer
git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
    $PHP_CS_FIXER_DIR fix --config=$CONFIG_FILE_DIR "$line" || FAILED=1;

    if [ $FAILED == 1 ]; then
      echo "Failed to run php-cs-fixer" && exit 1
    else
       git add "$line";
    fi
done
